create schema products_svc;

create sequence products_svc.id_gen start with 1 increment by 10;

create type products_svc.product_type AS ENUM ('PLANT', 'SEED' ,'SUPPLIES','TOOLS');


create table products_svc.products (
  product_id bigint generated by default as identity not null,
  product_name character varying not null default ''::character varying,
  product_description character varying null default ''::character varying,
  product_wiki_link character varying null default ''::character varying,
  product_resource_links character varying[] not null default '{}'::character varying[],
  price real not null default '10'::real,
  discount real not null default '0'::real,
  product_type products_svc.product_type not null default 'PLANT'::products_svc.product_type,
  constraint products_pkey primary key (product_id),
  constraint products_product_id_key unique (product_id),
  constraint products_price_check check ((price > (0)::double precision)),
  constraint products_discount_check check (
    (
      (discount > (0)::double precision)
      and (discount < (100)::double precision)
    )
  )
) TABLESPACE pg_default;

grant select on products_svc.products to postgres;
grant insert on products_svc.products to postgres;
grant update on products_svc.products to postgres;
grant delete on products_svc.products to postgres;